# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://rcdesignbureau.com'
baseurl: ''
title: 'RC Design Bureau'
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: US/Pacific # Timezone for blog posts and alike
logo: "assets/logos/logo@180px.png"
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

custom_fonts:
  primary: Arial


# Header nav
navigation_header:
- title: Home
  url: /
- title: About Us
  url: /about/
- title: Our Products
  url: https://store.rcdesignbureau.com
- title: Docs
  url: /rcdb-docs/
- title: Subreddit
  url: https://www.reddit.com/r/rcdesignbureau/

# Footer nav
navigation_footer:
- title:
  url:


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: product # Set the default layout for products