# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://rcdesignbureau.net'
baseurl: '/'
title: 'RC Design Bureau'
permalink: pretty
logo: "assets/logo.svg"
fonts:
  primary: Arial


# Header nav
navigation_header:
- title: Home
  url: /
- title: About Us
  url: /about/
- title: Our Products
  url: /products/
- title: Docs
  url: /rcdb-docs/
- title: Subreddit
  url: https://www.reddit.com/r/rcdesignbureau/

# Footer nav
navigation_footer:
- title:
  url:

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Updates from our Team"
    feature_image: "https://picsum.photos/2560/600?image=866"
  products:
    title: Products
    output: true
    description: "Our Products"


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: product # Set the default layout for products